// ============================================
// CHAPTERS/04-METHODOLOGY.TYP
// ============================================

= Methodology

== Research Design

This study adopts an exploratory, computational research design grounded in pattern recognition and machine learning to address the stated research objectives. The design is exploratory because it seeks to uncover latent antimicrobial resistance (AMR) structures that are not explicitly defined by existing categorical labels, rather than testing predefined hypotheses or establishing causal relationships. It is computational in nature because the primary contribution of the study lies in the design, implementation, and evaluation of a data-driven analytical framework for resistance pattern discovery and validation.

The research design integrates unsupervised learning for resistance structure discovery with supervised learning used exclusively as an external validation mechanism. Unsupervised methods are employed to identify resistance patterns based solely on phenotypic similarity in antimicrobial susceptibility testing (AST) data, without incorporating biological, environmental, or geographic labels during the discovery phase. Supervised learning is subsequently applied to assess the discriminative capacity and robustness of the discovered patterns, thereby addressing the limitations of unsupervised clustering when used in isolation.

The methodological strategy follows a staged, leakage-aware pipeline consisting of: (1) data preprocessing and feature engineering, (2) unsupervised resistance pattern discovery, (3) supervised validation, (4) integrated system design, and (5) quantitative evaluation. Throughout the study, strict separation is maintained between pattern discovery and interpretation to prevent information leakage and circular reasoning. The study is associational and descriptive in scope; no biological mechanisms, epidemiological transmission pathways, or clinical outcomes are inferred.

== Data Source and Description

=== Dataset Provenance

The dataset analyzed in this study was generated by the *INOHAC AMR Project Two* research team as part of an environmental antimicrobial resistance surveillance initiative. The present study did not involve primary sampling or laboratory experimentation. All analyses were conducted as a *secondary analysis* of phenotypic AST data collected by the source project.

The dataset comprises AST results for bacterial isolates obtained from environmental and aquaculture-associated sources across three geographic regions in the Philippines. The geographic distribution of isolates is summarized in *Table 4.1*.

#figure(
  table(
    columns: 3,
    table.header[*Region*][*National Code*][*Local Sites*],
    [Eastern Visayas (Ormoc)], [O], [Alegria, Larrazabal],
    [Central Luzon (Pampanga)], [P], [San Gabriel, San Roque],
    [BARMM (Marawi)], [M], [APMC, Dayawan, Gadongan, Tuca Kialdan],
  ),
  caption: [Geographic Distribution of Isolates],
) <tab:geographic-distribution>

=== Sample Source Categories

Isolates originated from environmental matrices representing the *Water–Fish interface* within the broader Water–Fish–Human nexus. These source categories capture exposure pathways relevant to environmental AMR dissemination and were used exclusively as contextual metadata during interpretation. Source categories are listed in *Table 4.2*.

#figure(
  table(
    columns: 3,
    table.header[*Source Code*][*Source Type*][*Description*],
    [DW], [Drinking Water], [Community water sources],
    [LW], [Lake Water], [Natural water bodies],
    [RW], [River Water], [Flowing water systems],
    [EWU], [Effluent Water (Untreated)], [Hospital or facility discharge (Human interface)],
    [EWT], [Effluent Water (Treated)], [Processed effluent discharge (Human interface)],
    [FB, FG, FT, FK], [Fish], [Banak, Gusaw, Tilapia, Kaolang],
  ),
  caption: [Sample Source Categories],
) <tab:sample-source-categories>

*Note:* While direct human clinical isolates are not included, effluent water samples (EWU, EWT) represent the anthropogenic component of the nexus, capturing resistance patterns potentially influenced by human antibiotic use and healthcare facility discharge.

=== Isolate Identification Convention

Each isolate was assigned a structured alphanumeric identifier encoding species, geographic origin, source type, replicate number, and colony number using the format:

```
[Species Prefix]_[Region][Site][Source][Replicate]C[Colony]
```

This convention enables systematic metadata parsing while preserving traceability throughout the analytical pipeline.

=== Antimicrobial Panel

Phenotypic AST data were generated using a panel of *22 antibiotics spanning 12 antimicrobial classes*, including an ESBL screening indicator. The antimicrobial panel is summarized in *Table 4.3*.

#figure(
  table(
    columns: 2,
    table.header[*Antimicrobial Class*][*Antibiotics*],
    [Penicillins], [Ampicillin],
    [β-lactam/β-lactamase inhibitors], [Amoxicillin/Clavulanic Acid],
    [Cephalosporins (1st gen.)], [Cefalexin, Cefalotin],
    [Cephalosporins (3rd/4th gen.)], [Cefpodoxime, Cefotaxime, Cefovecin, Ceftiofur],
    [Advanced cephalosporins], [Ceftaroline, Ceftazidime/Avibactam],
    [Carbapenems], [Imipenem],
    [Aminoglycosides], [Amikacin, Gentamicin, Neomycin],
    [Quinolones / Fluoroquinolones], [Nalidixic Acid, Enrofloxacin, Marbofloxacin, Pradofloxacin],
    [Tetracyclines], [Doxycycline, Tetracycline],
    [Nitrofurans], [Nitrofurantoin],
    [Phenicols], [Chloramphenicol],
    [Folate pathway inhibitors], [Trimethoprim/Sulfamethoxazole],
    [Resistance indicator], [ESBL screening],
  ),
  caption: [Antimicrobial Panel Composition],
) <tab:antimicrobial-panel>

== Study Area and Population

[Detail where and with whom/what the study was conducted]

== Sample Collection and Processing

[Explain sampling procedures]

#figure(
  table(
    columns: 4,
    table.header[*Sample Type*][*Location*][*Quantity*][*Collection Method*],
    [Water], [Rivers/Lakes], [n=100], [Grab sampling],
    [Fish], [Markets], [n=50], [Random selection],
    [Human], [Communities], [n=80], [Stool samples],
  ),
  caption: [Sample Collection Summary],
) <tab:samples>

== Laboratory Analysis

[Describe microbiological and molecular methods]

== Data Analysis

[Explain statistical and pattern recognition methods]

$ 
"Resistance Index" = sum_(i=1)^n (w_i times r_i) / n
$

where $w_i$ is the weight and $r_i$ is the resistance value.


